 #
 # Route  for questionnaire
 #
itech_sup_list_questionnaire:
    path:     /questionnaires
    defaults: { _controller: ItechSupQuestionnaireBundle:UserQuestionnaire:indexQuestionnaire}

itech_sup_gestion:
    path:     /gestion
    defaults: { _controller: ItechSupQuestionnaireBundle:UserQuestionnaire:indexGestion}

itech_sup_questionnaire:
    path:     /questionnaire/{questionnaire}
    defaults: { _controller: ItechSupQuestionnaireBundle:UserQuestionnaire:displayQuestionnaire}
    requirements:
        questionnaire:  \d+ 

itech_sup_questionnaire_succes_formulaire:
    path:     /success_questionnaire
    defaults: { _controller: ItechSupQuestionnaireBundle:UserQuestionnaire:succesFormulaire}

 #
 # Route  for gestion questionnaire
 #

itech_sup_gestionnaire_add_questionnaire:
    path:     /gestion/questionnaire/add
    defaults: { _controller: ItechSupQuestionnaireBundle:Questionnaire:addQuestionnaire}

itech_sup_gestionnaire_remove_questionnaire:
    path:     /gestion/questionnaire/remove/{questionnaire}
    defaults: { _controller: ItechSupQuestionnaireBundle:Questionnaire:removeQuestionnaire}
    requirements:
        questionnaire:  \d+ 
        
itech_sup_gestionnaire_update_questionnaire:
    path:     /gestion/questionnaire/update/{questionnaire}
    defaults: { _controller: ItechSupQuestionnaireBundle:Questionnaire:updateQuestionnaire}
    requirements:
        questionnaire:  \d+ 
        
#
# Route  for gestion categorie
#
itech_sup_gestionnaire_add_categorie:
    path:     /gestion/categorie/add
    defaults: { _controller: ItechSupQuestionnaireBundle:Categorie:addCategorie}

itech_sup_gestionnaire_remove_categorie:
    path:     /gestion/categorie/remove/{categorie}
    defaults: { _controller: ItechSupQuestionnaireBundle:Categorie:removeCategorie}
    requirements:
        questionnaire:  \d+ 
        
itech_sup_gestionnaire_update_categorie:
    path:     /gestion/categorie/update/{categorie}
    defaults: { _controller: ItechSupQuestionnaireBundle:Categorie:updateCategorie}
    requirements:
        questionnaire:  \d+ 
        
#
# Route  for gestion question
#
itech_sup_gestionnaire_add_question:
    path:     /gestion/question/add
    defaults: { _controller: ItechSupQuestionnaireBundle:Question:addQuestion}

itech_sup_gestionnaire_remove_question:
    path:     /gestion/question/remove/{question}
    defaults: { _controller: ItechSupQuestionnaireBundle:Question:removeQuestion}
    requirements:
        questionnaire:  \d+ 
        
itech_sup_gestionnaire_update_question:
    path:     /gestion/question/update/{question}
    defaults: { _controller: ItechSupQuestionnaireBundle:Question:updateQuestion}
    requirements:
        questionnaire:  \d+ 